### ISSUE TITLE
The bot joins the VC but does not play music

### ISSUE THREAD

**Issue by DiscordNoobyDev** [CTK-WARRIOR/24-7-Discord-Music-Bot#27]
MinigetError: Status code: 410
    at ClientRequest.<anonymous> (/home/runner/24-7-Discord-Music-Bot/node_modules/miniget/dist/index.js:210:27)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at TLSSocket.Readable.push (_stream_readable.js:213:10) {
  statusCode: 410
}
Error code

**Comment by CTK-WARRIOR** [comment]
No soulution for now

**Comment by DiscordNoobyDev** [comment]
it's minor error or smth to do with the API

**Comment by CTK-WARRIOR** [comment]
Well, it just disappears after some time, no exact solution for now but you can try using cookies and stuff.
